### PR TITLE
Add GitHub Actions configuration

### PR DESCRIPTION
**Pull request by joel-coffman**
This change enables continuous integration (CI) testing using GitHub
Actions. Testing is currently limited to the execution of setup.sh to
install and configure all the services -- i.e., if this script
executes without failure, then the tests pass.

Further testing could be performed following the installation of
services. For example, after installing Apache and PHP, a web page
could be accessed to verify that the web page is rendered correctly.

GitHub Actions: https://github.com/features/actions

### CODE REVIEW

**Comment by ndujfxhufv** [comment]
Ok

**Comment by joel-coffman** [comment]
Need to test using virtual machine (VM) prior to merging this pull request.

**Comment by joel-coffman** [comment]
> Need to test using virtual machine (VM) prior to merging this pull request.

Verified using Ubuntu 18.04 with VMware Workstation 16.2.1.

**Comment by joel-coffman** [comment]
> Need to test using virtual machine (VM) prior to merging this pull request.

Verified using Ubuntu 18.04 with VMware Workstation 16.2.1.

**Comment by joel-coffman** [comment]
> Need to test using virtual machine (VM) prior to merging this pull request.

Verified using Ubuntu 18.04 with VMware Workstation 16.2.1.

**Pull request merged**
